version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: techtitans
      POSTGRES_PASSWORD: capstone
      POSTGRES_DB: RoarinDealsDB
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql